# Generated by Django 3.2.9 on 2023-12-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='o131',
            new_name='o31',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='o132',
            new_name='o32',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='o133',
            new_name='o33',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='o134',
            new_name='o34',
        ),
    ]
